FROM quay.io/fedora/fedora:39-x86_64

USER root

RUN dnf upgrade --setopt install_weak_deps=false -y && dnf -y clean all && rm -rf /var/cache/yum
RUN dnf update -y
RUN dnf install -y \
  vim \
  curl \
  wget \
  fish

WORKDIR /root
CMD ["fish"]
