FROM quay.io/fedora/fedora:42-x86_64 AS fedora

USER root

RUN dnf upgrade --setopt install_weak_deps=false -y #&& dnf -y clean all && rm -rf /var/cache/yum
RUN dnf update -y
RUN dnf install -y \
  vim \
  curl \
  wget \
  fish

# RUN dnf -y clean all && rm -rf /var/cache/yum

WORKDIR /root
CMD ["fish"]
