FROM docker.io/semaphoreui/semaphore:beta

USER root
RUN apk del ansible
RUN apk add --no-cache py3-pip
RUN rm -rf /var/cache/apk/*

WORKDIR /home/semaphore
USER 1001

ENV PATH="${PATH}:/home/semaphore/.local/bin"
ENV ANSIBLE_LIBRARY="/home/semaphore/.local/lib/python3.11/site-packages/ansible/modules"
ENV ANSIBLE_COLLECTIONS_PATH="/home/semaphore/.local/lib/python3.11/site-packages/ansible/collections/"
ENV PYTHONPATH="/home/semaphore/.local/lib/python3.11/site-packages"

RUN pip3 install ansible==9.2.0 prettytable
